import json
import os
from huggingface_hub import HfApi, create_repo, upload_folder

KB_FILE = "success_kb.json"
EXPORT_FILE = "finetune_data.jsonl"
REPO_NAME = "sases-finetune-data"

def export_data():
    """导出微调数据为 JSONL"""
    if not os.path.exists(KB_FILE):
        print(f"知识库文件 {KB_FILE} 不存在")
        return 0

    with open(KB_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    with open(EXPORT_FILE, "w", encoding="utf-8") as out:
        for item in data:
            task = item.get("task", "")
            solution = item.get("solution", "")
            record = {
                "messages": [
                    {"role": "user", "content": f"任务：{task}\n请写出一个完整可运行的Python函数。只需输出代码。"},
                    {"role": "assistant", "content": solution}
                ]
            }
            out.write(json.dumps(record, ensure_ascii=False) + "\n")

    print(f"已导出 {len(data)} 条数据")
    return len(data)

def generate_readme(count):
    """生成新的数据集卡片 README 内容"""
    readme_content = f"""---
license: apache-2.0
task_categories:
- text-generation
language:
- zh
- en
---

# SASES Fine-tune Dataset

Dataset generated by the SASES seed architecture self-iteration loop.

## Data Size
{count} successful trajectories

## Format
Each line is a JSON object with `messages` field (instruction fine-tuning format).

## Usage
For fine-tuning code generation models to learn the SASES generate-verify-backtrack workflow.

## Generation Method
- Seed tasks generated with domain rotation and semantic deduplication
- Solutions verified in sandbox with test cases
- Only successful trajectories are stored

## License
Apache 2.0
"""
    return readme_content

def upload():
    count = export_data()
    if count == 0:
        print("没有数据可上传，退出。")
        return

    # 创建临时目录存放数据集和 README
    os.makedirs("hf_upload", exist_ok=True)
    os.replace(EXPORT_FILE, f"hf_upload/{EXPORT_FILE}")

    # 生成并写入新的 README
    readme_text = generate_readme(count)
    with open("hf_upload/README.md", "w", encoding="utf-8") as f:
        f.write(readme_text)

    # 创建或获取仓库
    api = HfApi()
    user = api.whoami()["name"]
    repo_id = f"{user}/{REPO_NAME}"

    try:
        create_repo(repo_id, repo_type="dataset", exist_ok=True)
        print(f"仓库已就绪: {repo_id}")
    except Exception as e:
        print(f"创建仓库失败: {e}")
        return

    # 上传整个文件夹
    upload_folder(
        folder_path="hf_upload",
        repo_id=repo_id,
        repo_type="dataset",
        commit_message=f"Update dataset with new README ({count} records)"
    )

    print(f"上传完成: https://huggingface.co/datasets/{repo_id}")

if __name__ == "__main__":
    upload()
